name: Build FF14 Controller APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        sudo apt install -y libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly
        sudo apt install -y libgstreamer-plugins-base1.0-dev libgstreamer-plugins-good1.0-dev libgstreamer-plugins-bad1.0-dev
        sudo apt install -y liblzma-dev libbz2-dev libreadline-dev libsqlite3-dev libgdbm-dev libdb-dev
        sudo apt install -y xvfb

    - name: Force Python 3.8 usage
      run: |
        python3.8 --version
        python3.8 -m pip install --upgrade pip
        sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.8 1

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('requirements_ff14_android.txt') }}

          unzip \
          openjdk-8-jdk \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          cmake \
          libffi-dev \
          libssl-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.33
        pip install --upgrade setuptools wheel

    - name: Accept Android SDK licenses
      run: |
        mkdir -p ~/.android
        echo 'count=0' > ~/.android/repositories.cfg
        echo y | buildozer android debug || echo "First run to setup SDK"
        
    - name: Accept all SDK licenses
      run: |
        find ~/.buildozer -name "sdkmanager" 2>/dev/null | head -1 | xargs -I {} bash -c 'yes | {} --licenses' || true
        
    - name: Clean previous builds
      run: |
        rm -rf .buildozer/
        rm -rf bin/
        
    - name: Initialize Buildozer
      run: |
        buildozer init || echo "buildozer.spec already exists"
        
    - name: Build Android APK
      run: |
        echo "Building Android APK with stable PyJNIus 1.6.1..."
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: FF14Controller-APK
        path: bin/*.apk
        retention-days: 30

    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: FF14 Controller v1.0.${{ github.run_number }}
        body: |
          ## FF14 Controller para Android
          
          ### Instalación:
          1. Descarga el archivo APK
          2. Activa "Orígenes desconocidos" en tu tableta Android
          3. Instala el APK
          4. Ejecuta el servidor en tu PC
          5. ¡Disfruta jugando FF14!
          
          ### Controles incluidos:
          - Números 1-9, 0, -, =
          - Teclas F1-F12
          - Controles PS5 mapeados
          - Macros especiales para FF14
          
          ### Changelog:
          - Versión inicial con todas las funcionalidades
        files: bin/*.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
